# based off of https://github.com/aws-samples/amazon-ec2-image-builder-samples/tree/master/CloudFormation/Linux/amazon-linux-2-with-latest-ssm-agent
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AwsOrganizationId:
    Description: Share the generated image with this Organization
    Type: String
    Default: "o-69lcdj4kro"
  ImageVersion:
    Description: The generated image version.
    Type: String
    Default: "0.0.0"
  VolumeSize:
    Description: The EBS volume size (in GB)
    Type: Number
    Default: 32
    MinValue: 8
    MaxValue: 500
Resources:
  # By default, AWS Services do not have permission to perform actions on your instances. This grants
  # AWS Systems Manager (SSM) and EC2 Image Builder the necessary permissions to build an image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  # https://docs.aws.amazon.com/imagebuilder/latest/userguide/image-builder-setting-up.html
  InstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'ec2.${AWS::URLSuffix}'
        Version: '2012-10-17'
      Path: /executionServiceEC2Role/
  # To pass the InstanceRole to an EC2 instance, we need an InstanceProfile.
  # This profile will be used during the image build process.
  # https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /executionServiceEC2Role/
      Roles:
        - Ref: InstanceRole

  # Specifies the infrastructure within which to build and test your image.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html
  ImageInfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub '${AWS::StackName}-Configuration'
      InstanceProfileName:
        Ref: InstanceProfile

  InstallComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub '${AWS::StackName}-component'
      Platform: Linux
      Version: !Ref ImageVersion
      Description: 'Install Docker and Docker Compose on Amazon Linux 2023'
      SupportedOsVersions:
        - 'Amazon Linux 2023'
      Data: |
        name: install-docker
        description: Install Docker and Docker Compose on Amazon Linux 2023
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallPackages
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - dnf install -y spal-release  # needed for docker compose
                    - dnf install -y docker-compose git psutils python3-pip python3-wheel
                    - dnf install -y gcc python3-devel  # needed to build psutil python wheel for synapseclient
                    - pip3 install --upgrade synapseclient[pandas,pysftp]
                    - systemctl enable docker
              - name: GroupMembership
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - usermod -a -G docker,wheel ec2-user
                    - adduser -m -s /bin/bash -G docker,wheel ssm-user
          - name: test
            steps:
              - name: TestPackages
                action: ExecuteBash
                inputs:
                  commands:
                    - set -e
                    - docker compose ls
                    - python3 -c "import synapseclient, pandas, pysftp; print('Python packages verified')"

  # Recipe which references the latest (x.x.x) version of the Amazon Linux 2023 AMI).
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html
  ImageRecipeX86:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Sub '${AWS::StackName}-x86'
      Version: !Sub ${ImageVersion}
      ParentImage: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:image/amazon-linux-2023-x86/x.x.x
      Components:
        - ComponentArn: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:component/update-linux/x.x.x
        - ComponentArn: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:component/amazon-cloudwatch-agent-linux/x.x.x
        - ComponentArn: !Ref InstallComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref VolumeSize
            Encrypted: False  # Needed for public images
      AdditionalInstanceConfiguration:
        UserDataOverride:
          Fn::Base64: |
            #!/bin/bash -eu

            # This script runs when the EC2 instance boots
            # Make sure the latest package versions are installed on the host

            # update system packages
            sudo dnf upgrade -y

            # update python packages
            sudo pip3 install --upgrade synapseclient[pandas,pysftp]
            sudo pip3 freeze

  # Recipe which references the latest (x.x.x) version of the Amazon Linux 2023 AMI).
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html
  ImageRecipeArm64:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Sub '${AWS::StackName}-arm64'
      Version: !Sub ${ImageVersion}
      ParentImage: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:image/amazon-linux-2023-arm64/x.x.x
      Components:
        - ComponentArn: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:component/update-linux/x.x.x
        - ComponentArn: !Sub arn:aws:imagebuilder:${AWS::Region}:aws:component/amazon-cloudwatch-agent-linux/x.x.x
        - ComponentArn: !Ref InstallComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref VolumeSize
            Encrypted: False  # Needed for public images
      AdditionalInstanceConfiguration:
        UserDataOverride:
          Fn::Base64: |
            #!/bin/bash -eu

            # This script runs when the EC2 instance boots
            # Make sure the latest package versions are installed on the host

            # update system packages
            sudo dnf upgrade -y

            # update python packages
            sudo pip3 install --upgrade synapseclient[pandas,pysftp]
            sudo pip3 freeze

  # The Image resource will show complete in CloudFormation once your image is done building. Use this resource later in your
  # stack to reference the image within other resources.
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-image.html
  ImageX86:
    Type: AWS::ImageBuilder::Image
    Properties:
      ImageRecipeArn:
        Ref: ImageRecipeX86
      InfrastructureConfigurationArn:
        Ref: ImageInfrastructureConfiguration
      DistributionConfigurationArn:
        Ref: ImageDistributionConfiguration
      Tags:
        Name: !Sub '${AWS::StackName}-x86'

  ImageArm64:
    Type: AWS::ImageBuilder::Image
    Properties:
      ImageRecipeArn:
        Ref: ImageRecipeArm64
      InfrastructureConfigurationArn:
        Ref: ImageInfrastructureConfiguration
      DistributionConfigurationArn:
        Ref: ImageDistributionConfiguration
      Tags:
        Name: !Sub '${AWS::StackName}-arm64'

  ImageDistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Sub '${AWS::StackName}-Distributions'
      Distributions:
        - Region: !Ref 'AWS::Region'
          AmiDistributionConfiguration:
            AmiTags:    # apply tags to generated AMIs
              Name: !Sub '${AWS::StackName}'
            LaunchPermissionConfiguration:
              OrganizationArns:
                - !Sub 'arn:${AWS::Partition}:organizations::${AWS::AccountId}:organization/${AwsOrganizationId}'
              UserGroups:
                - all   # Make AMI globally public
