# from https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/Explode
Transform: AWS::Serverless-2016-10-31

Resources:
  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: lambda
      Handler: explode.handler

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Explode
      FunctionName: !GetAtt MacroFunction.Arn
