AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Setup to authorize the VPC Peering request from a specific account
  https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/solutions/VPCPeering
Parameters:
  VpcPeeringRequesterAwsAccountId:
    Type: String
    NoEcho: true
    Description: The AWS account running the VPN
    AllowedPattern: '[0-9]*'
    ConstraintDescription: Must be account number without dashes
Resources:
  AuthorizerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${VpcPeeringRequesterAwsAccountId}:root'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: VPCAuthorizer
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:AcceptVpcPeeringConnection'
                Resource:
                  - '*'
Outputs:
  AuthorizerRoleArn:
    Description: Cross account authorizer role ARN
    Value: !GetAtt AuthorizerRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AuthorizerRoleArn'
