AWSTemplateFormatVersion: 2010-09-09
Description: NextFlow Tower Launch
Parameters:
  EcsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for ECS cluster to grant database access
  SubnetIds:
    Type: CommaDelimitedList
    Description: List of public Subnet Ids for the load balancer
  MaxvCpus:
    Type: Number
    Description: The number of max CPUs for Batch compute environments
    MinValue: 1
    MaxValue: 16
    Default: 1
Resources:
  UserManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Stmt1530313170000
            Effect: Allow
            Action:
              - batch:CancelJob
              - batch:RegisterJobDefinition
              - batch:DescribeComputeEnvironments
              - batch:DescribeJobDefinitions
              - batch:DescribeJobQueues
              - batch:DescribeJobs
              - batch:ListJobs
              - batch:SubmitJob
              - batch:TerminateJob
            Resource:
              - '*'
  JobManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - batch:DescribeJobQueues
              - batch:CancelJob
              - batch:SubmitJob
              - batch:ListJobs
              - batch:DescribeComputeEnvironments
              - batch:TerminateJob
              - batch:DescribeJobs
              - batch:RegisterJobDefinition
              - batch:DescribeJobDefinitions
              - ecs:DescribeTasks
              - ec2:DescribeInstances
              - ec2:DescribeInstanceTypes
              - ec2:DescribeInstanceAttribute
              - ecs:DescribeContainerInstances
              - ec2:DescribeInstanceStatus
              - logs:Describe*
              - logs:Get*
              - logs:List*
              - logs:StartQuery
              - logs:StopQuery
              - logs:TestMetricFilter
              - logs:FilterLogEvents
            Resource: '*'
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - !Ref JobManagedPolicy
  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
  ComputeEnvironmentOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3008
    Properties:
      Type: MANAGED
      State: ENABLED
      ServiceRole: !Ref BatchServiceRole
      ComputeResources:
        Type: EC2
        MaxvCpus: !Ref MaxvCpus
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref EcsSecurityGroupId
        InstanceRole: !Ref InstanceRole
        LaunchTemplate:
          LaunchTemplateId: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplate'
          LaunchTemplateName: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplate'
          Version: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplateLatestVersionNumber'
  ComputeEnvironmentSpot:
    Type: AWS::Batch::ComputeEnvironment
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3008
    Properties:
      Type: MANAGED
      State: ENABLED
      ServiceRole: !Ref BatchServiceRole
      ComputeResources:
        Type: SPOT
        MaxvCpus: !Ref MaxvCpus
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref EcsSecurityGroupId
        SpotIamFleetRole: !Ref SpotFleetRole
        InstanceRole: !Ref InstanceRole
        LaunchTemplate:
          LaunchTemplateId: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplate'
          LaunchTemplateName: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplate'
          Version: !ImportValue
            'Fn::Sub': '${AWS::Region}-nextflow-ecs-cluster-EcsLaunchTemplateLatestVersionNumber'
  JobQueueOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnvironmentOnDemand
          Order: 1
      Priority: 1
      State: ENABLED
  JobQueueSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnvironmentSpot
          Order: 1
      Priority: 1
      State: ENABLED
Outputs:
  BatchServiceRole:
    Value: !Ref BatchServiceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BatchServiceRole'
  InstanceRole:
    Value: !Ref InstanceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-InstanceRole'
  SpotFleetRole:
    Value: !Ref SpotFleetRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SpotFleetRole'
  ComputeEnvironmentOnDemand:
    Value: !Ref ComputeEnvironmentOnDemand
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ComputeEnvironmentOnDemand'
  ComputeEnvironmentSpot:
    Value: !Ref ComputeEnvironmentSpot
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ComputeEnvironmentSpot'
  JobQueueOnDemand:
    Value: !Ref JobQueueOnDemand
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-JobQueueOnDemand'
  JobQueueSpot:
    Value: !Ref JobQueueSpot
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-JobQueueSpot'
