AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Setup cost anomaly detection to monitor AWS services
Parameters:
  Threshold:
    Type: Number
    Default: 500
    Description: The dollar value that triggers a notification if the threshold is exceeded.
  Frequency:
    Type: String
    Default: 'DAILY'
    Description: The frequency that anomaly reports are sent over email
    AllowedValues:
      - 'DAILY'
      - 'IMMEDIATE'
      - 'WEEKLY'
  Subscribers:
    Type: List<String>
    Description: >-
      A dictionary list of subscribers (i.e. [{"Type": "EMAIL", "Address": "abc@acme.com"},{"Type": "EMAIL", "Address": "def@acme.com"}])
      https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ce-anomalysubscription.html
Conditions:
  HasSubscribers: !Not
    - !Equals
      - !Join ["", !Ref Subscribers]
      - ''
Resources:
  AnomalyServiceMonitor:
    Type: 'AWS::CE::AnomalyMonitor'
    Properties:
      MonitorName: 'services-anomaly'
      MonitorType: 'DIMENSIONAL'
      MonitorDimension: 'SERVICE'
  AnomalySubscription:
    Metadata:
      cfn-lint:
        config:
          ignore_checks: [E3002]
    Type: 'AWS::CE::AnomalySubscription'
    Condition: HasSubscribers
    Properties:
      SubscriptionName: "services-anomaly-subscription"
      Threshold: !Ref Threshold
      Frequency: !Ref Frequency
      MonitorArnList:
        - !Ref AnomalyServiceMonitor
      Subscribers: !Ref Subscribers
