# org-formatino template to configure AWS SSO
# from https://github.com/org-formation/org-formation-reference/tree/master/src/templates/100-aws-sso
AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:

  instanceArn:
    Type: String

  principalId:
    Type: String

  permissionSetArn:
    Type: String
    Default: ''

  permissionSetName:
    Type: String
    Default: AdministratorAccess

  managedPolicies:
    Type: CommaDelimitedList
    Default: ''
    Description: 'A list of AWS managed policy ARNs for a SSO permission set'

  inlinePolicy:
    Type: String
    Default: ''
    Description: 'An AWS policy document for a SSO permission set'

  sessionDuration:
    Type: String
    Default: PT1H

  masterAccountId:
    Type: String
    Default: ''

Conditions:

  includePermissionSet: !Equals [ '', !Ref permissionSetArn ]
  includeMaster: !Not [ !Equals [ '', !Ref masterAccountId ] ]
  includeInlinePolicy: !Not [ !Equals [ '', !Ref inlinePolicy ] ]
  includeManagedPolicies: !Not
    - !Equals
      - !Join ['', !Ref managedPolicies]
      - ''

Resources:

  PermissionSet:
    Type: AWS::SSO::PermissionSet
    Condition: includePermissionSet
    Properties:
      Name: !Ref permissionSetName
      Description: !Sub '${permissionSetName} access to AWS organization'
      InstanceArn: !Ref instanceArn
      ManagedPolicies: !If [ includeManagedPolicies, !Ref managedPolicies, !Ref 'AWS::NoValue' ]
      SessionDuration: !Ref sessionDuration
      InlinePolicy: !If [ includeInlinePolicy, !Ref inlinePolicy, !Ref 'AWS::NoValue' ]

  AssignmentMaster:
    Type: AWS::SSO::Assignment
    Condition: includeMaster
    Properties:
      InstanceArn: !Ref instanceArn
      PermissionSetArn: !If [ includePermissionSet, !GetAtt PermissionSet.PermissionSetArn, !Ref permissionSetArn ]
      PrincipalId: !Ref principalId
      PrincipalType: GROUP
      TargetType: AWS_ACCOUNT
      TargetId: !Ref masterAccountId

  AssignmentGroup:
    Metadata:
      cfn-lint:
        config:
          ignore_checks: [E1029]
    Type: Community::SSO::AssignmentGroup
    Properties:
      InstanceArn: !Ref instanceArn
      PermissionSets:
        - !If [ includePermissionSet, !GetAtt PermissionSet.PermissionSetArn, !Ref permissionSetArn ]
      PrincipalId: !Ref principalId
      PrincipalType: GROUP
      Targets:
        - TargetType: AWS_ACCOUNT
          TargetIds:
            - Fn::EnumTargetAccounts TargetBinding ${account}

Outputs:
  PermissionSetArn:
    Value: !If [ includePermissionSet, !GetAtt PermissionSet.PermissionSetArn, !Ref permissionSetArn ]
    Export:
      Name: !Sub ${AWS::StackName}-permission-set-arn
