Description: Maintenance tasks for scipoolprod instances
AWSTemplateFormatVersion: 2010-09-09
Resources:
  DefaultMaintenanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties:
      Name: ProdDefaultMaintenanceWindow
      Description: Automated deliver patches every other Sunday
      Duration: 3
      Cutoff: 1
      Schedule: 'cron(00 10 ? * SUN/2 *)' #1000UTC Every other Sunday
      ScheduleTimezone: 'UTC'
      AllowUnassociatedTargets: false
  DefaultPatchGroupTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      Description: "Instances tagged PatchGroup=prod-default"
      ResourceType: INSTANCE
      WindowId:
        Ref: DefaultMaintenanceWindow
      Targets:
        - Key: 'tag:PatchGroup'
          Values:
            - 'prod-default'  #Current we have only one group
  ManagedInstanceMaintenanceTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      Description: "Instances tagged ManagedInstanceMaintenanceTarget=yes"
      ResourceType: INSTANCE
      WindowId:
        Ref: DefaultMaintenanceWindow
      Targets:
        - Key: 'tag:ManagedInstanceMaintenanceTarget'
          Values:
            - 'yes'
  MaintenanceWindowRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  MaintenanceWindowAgentUpdateTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      Description: AWS-UpdateSSMAgent task run during DefaultMaintenanceWindow
      ServiceRoleArn: !GetAtt MaintenanceWindowRole.Arn
      Priority: 1
      MaxErrors: '1'
      MaxConcurrency: '2'
      Targets:
        - Key: WindowTargetIds
          Values:
            - Ref: ManagedInstanceMaintenanceTarget
      TaskType: RUN_COMMAND
      WindowId:
        Ref: DefaultMaintenanceWindow
      TaskArn: AWS-UpdateSSMAgent
  MaintenanceWindowPatchTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      Description: AWS-RunPatchBaseline task run during DefaultMaintenanceWindow
      ServiceRoleArn: !GetAtt MaintenanceWindowRole.Arn
      Priority: 2
      MaxErrors: '1'
      MaxConcurrency: '2'
      Targets:
        - Key: WindowTargetIds
          Values:
            - Ref: DefaultPatchGroupTarget
      TaskType: RUN_COMMAND
      WindowId:
        Ref: DefaultMaintenanceWindow
      TaskArn: AWS-RunPatchBaseline #Operate with default managed baselines
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation:
              - Install
            RebootOption:
              - RebootIfNeeded
