Description: Setup a hosted zone for DNS
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DnsDomainName:
    Description: A fully qualified domain name (i.e. sagebionetworks.org)
    Type: String
Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DnsDomainName}"
      Name: !Join ["", [!Ref DnsDomainName, "."]]
      HostedZoneTags:
        -
          Key: "Name"
          Value: !Ref AWS::StackName
Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-HostedZoneId'
  HostedZoneNameServers:
    Value: !Join
      - ','
      - !GetAtt HostedZone.NameServers
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-HostedZoneNameServers'
