# A service-linked role is a unique type of IAM role that is linked directly to an AWS service.
# Service-linked roles are predefined by the service and include all the permissions that the
# service requires to call other AWS services on your behalf.
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Provision AWS service linked roles
Resources:
  # EC2 requires a special service-linked role named `AWSServiceRoleForEC2Spot` to launch and manage Spot Instances
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#service-linked-roles-spot-instance-requests
  AWSServiceRoleForEC2Spot:
    Type: "AWS::IAM::ServiceLinkedRole"
    Properties:
      AWSServiceName: "spot.amazonaws.com"
      Description: "SLR for EC2 Spot"
  # Role for EC2 Spot Fleet to bid on, launch, tag, and terminate instances on your behalf
  # https://docs.aws.amazon.com/batch/latest/userguide/spot_fleet_IAM_role.html
  AWSServiceRoleForEC2SpotFleet:
    Type: "AWS::IAM::ServiceLinkedRole"
    Properties:
      AWSServiceName: "spotfleet.amazonaws.com"
      Description: "SLR for EC2 Spot Fleet"
  # Role to grant the Spot Fleet permission to request, launch, terminate, and tag instances on your behalf
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html
  AWSEC2SpotFleetTaggingRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "aws-ec2-spot-fleet-tagging-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - spotfleet.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
Outputs:
  AWSServiceRoleForEC2SpotId:
    Value: !Ref AWSServiceRoleForEC2Spot
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AWSServiceRoleForEC2SpotId'
  AWSServiceRoleForEC2SpotFleetId:
    Value: !Ref AWSServiceRoleForEC2SpotFleet
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AWSServiceRoleForEC2SpotFleetId'
  AWSEC2SpotFleetTaggingRoleArn:
    Value: !GetAtt AWSEC2SpotFleetTaggingRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AWSEC2SpotFleetTaggingRoleArn'
  AWSEC2SpotFleetTaggingRoleId:
    Value: !GetAtt AWSEC2SpotFleetTaggingRole.RoleId
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AWSEC2SpotFleetTaggingRoleId'
