AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Setup an AWS transit gateway attachment
Parameters:
  TransitGatewayId:
    Description: 'The transit gateway Id'
    Type: String
    AllowedPattern: '^tgw-[a-z0-9]+$'
    ConstraintDescription: 'Must be a transit gateway Id (i.e. tgw-1111148306e2d3b5)'
  VpcName:
    Description: 'The transit gateway will attach to this VPC Id'
    Type: String
Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      SubnetIds:
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-${VpcName}-PrivateSubnet'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-${VpcName}-PrivateSubnet1'
        - !ImportValue
          'Fn::Sub': '${AWS::Region}-${VpcName}-PrivateSubnet2'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !ImportValue
        'Fn::Sub': '${AWS::Region}-${VpcName}-VPCId'

Outputs:
  TransitGatewayAttachment:
    Description: This Is the transit gateway attachment
    Value: !Ref TransitGatewayAttachment
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-TransitGatewayAttachment'
