---
project:
  name: aws-infra
  owner: tcisagebio@sagebase.org
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  tags:
    owner: "taskcat"
tests:
  sumologic-role:
    parameters: sumologic-role-input.json
    regions:
      - us-east-1
    template: sumologic-role.yaml
  ParkMyCloud:
    parameters: ParkMyCloud-input.json
    regions:
      - us-east-1
    template: ParkMyCloud.yaml
  AccountAlertTopics:
    parameters: AccountAlertTopics-input.json
    regions:
      - us-east-1
    template: AccountAlertTopics.yaml
  jumpcloud:
    parameters: jumpcloud-input.json
    regions:
      - us-east-1
    template: jumpcloud.yaml
  # test depends on resources in Sage-Bionetworks/admincentral-infra/config/prod/taskcat.yaml
  AddSameRegionBucketDownloadRestriction:
    parameters: AddSameRegionBucketDownloadRestriction-input.json
    regions:
      - us-east-1
    template: AddSameRegionBucketDownloadRestriction.yaml
  bootstrap:
    parameters: bootstrap-input.json
    regions:
      - us-east-1
    template: bootstrap.yaml
  vpc:
    parameters: vpc-input.json
    regions:
      - us-east-1
    template: vpc.yaml
  ec2-backup:
    parameters: ec2-backup-input.json
    regions:
      - us-east-1
    template: ec2-backup.yaml

  # Tests disabled due to issue: https://github.com/aws-quickstart/taskcat/issues/278
  #  s3-bucket:
  #    parameter_input: s3-bucket-input.json
  #    regions:
  #      - us-east-1
  #    template_file: s3-bucket.yaml
  #  managed-batch:
  #    parameter_input: managed-batch-input.json
  #    regions:
  #      - us-east-1
  #    template_file: managed-batch.yaml


  # Stack deletion fails when taskcat attempts to delete bucket
  # s3web-bucket:
  #   parameter_input: s3web-bucket-input.json
  #   regions:
  #     - us-east-1
  #   template_file: managed-s3Web.yaml
  # Cloudfront adds to much time to the test (~60 mins to deploy and cleanup). Also taskcat fails to cleanup.
  # s3web-cloudfront-bucket:
  #   parameter_input: s3web-cloudfront-bucket-input.json
  #   regions:
  #     - us-east-1
  #   template_file: managed-s3WebCloudfront.yaml
