# Define a role
#
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a role'
Parameters:
  AssumeRolePolicyDocument:
    Type: String
    Description: Policy describing trust relationships
    Default: ''
  Policies:
    Type: String
    Description: In-line policy
    Default: ''
  ManagedPolicyArns:
    Type: String
    Description: ARNs of managed policies
    Default: ''
  MaxSessionDuration:
    Type: Integer
    Description: Maximum session duration in seconds
    Default: 43200
  RoleName:
    Type: String
    Description: Role name
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Ref AssumeRolePolicyDocument
      Policies: !Ref Policies
      ManagedPolicyArns: !Ref ManagedPolicyArns
      MaxSessionDuration: !Ref MaxSessionDuration
      RoleName: !Ref RoleName
Outputs:
  RoleName:
    Value: !Ref Role
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleName'
  RoleId:
    Value: !GetAtt Role.RoleId
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleId'
  RoleArn:
    Value: !GetAtt Role.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleArn'
