Description: Create an custom IAM managed policy
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PolicyDocument:
    Type: String
    Description: >-
      A JSON policy document to define a custom policy.
      Example:
        {
          "Version":"2012-10-17",
          "Statement":[
            {
              "Sid":"PublicRead",
              "Effect":"Allow",
              "Principal": "*",
              "Action":["s3:GetObject","s3:GetObjectVersion"],
              "Resource":["arn:aws:s3:::EXAMPLE-BUCKET/*"]
            }
          ]
        }
  PolicyName:
    Type: String
    Default: ''
Conditions:
  includeName: !Not [ !Equals [ '', !Ref PolicyName ] ]
Resources:
  ManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Ref PolicyDocument
      ManagedPolicyName: !If [ includeName, !Ref PolicyName, !Ref 'AWS::NoValue' ]
Outputs:
  ManagedPolicyArn:
    Value: !Ref ManagedPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ManagedPolicyArn'
