Description: Setup an AWS service account and role with a custom policy
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  PolicyDocument:
    Type: String
    Description: >-
      A JSON policy document to define a custom policy for the role.
      Example:
        {
          "Version":"2012-10-17",
          "Statement":[
            {
              "Sid":"PublicRead",
              "Effect":"Allow",
              "Principal": "*",
              "Action":["s3:GetObject","s3:GetObjectVersion"],
              "Resource":["arn:aws:s3:::EXAMPLE-BUCKET/*"]
            }
          ]
        }
Resources:
  ServiceUser:
    Type: 'AWS::IAM::User'
  ServiceUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref ServiceUser
  ServicePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument: !Ref PolicyDocument
  ServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - !Ref ServicePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !GetAtt ServiceUser.Arn
            Action:
              - "sts:AssumeRole"
Outputs:
  ServiceUser:
    Value: !Ref ServiceUser
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUser'
  ServiceUserArn:
    Value: !GetAtt ServiceUser.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserArn'
  ServiceUserAccessKey:
    Value: !Ref ServiceUserAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserAccessKey'
  ServiceUserSecretAccessKey:
    Value: !GetAtt ServiceUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserSecretAccessKey'
  ServiceRole:
    Value: !Ref ServiceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceRole'
  ServiceRoleArn:
    Value: !GetAtt ServiceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceRoleArn'
