Description: Setup an AWS service account and role
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ServiceUserPolicies:
    Type: CommaDelimitedList
Resources:
  ServiceUser:
    Type: 'AWS::IAM::User'
  ServiceUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref ServiceUser
  ServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns: !Ref ServiceUserPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !GetAtt ServiceUser.Arn
            Action:
              - "sts:AssumeRole"
Outputs:
  ServiceUser:
    Value: !Ref ServiceUser
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUser'
  ServiceUserArn:
    Value: !GetAtt ServiceUser.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserArn'
  ServiceUserAccessKey:
    Value: !Ref ServiceUserAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserAccessKey'
  ServiceUserSecretAccessKey:
    Value: !GetAtt ServiceUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceUserSecretAccessKey'
  ServiceRole:
    Value: !Ref ServiceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceRole'
  ServiceRoleArn:
    Value: !GetAtt ServiceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ServiceRoleArn'
