version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfn-set-bucket-tags-macro"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1akbohske1rfw"
s3_prefix = "cfn-set-bucket-tags-macro"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Department=SysBio Project=Infrastructure OwnerEmail=tess.thyer@sagebase.org"
