AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PasswordPolicy:
    Type: Community::IAM::PasswordPolicy
    Properties:
      MinimumPasswordLength: 18
      RequireLowercaseCharacters: true
      RequireUppercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      AllowUsersToChangePassword: false
      HardExpiry: false
      PasswordReusePrevention: 24
      MaxPasswordAge: 60
