AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  MinPasswordLength:
    Default: 16
    Description: The minimum length of a password
    Type: Number
    MinValue: 16

Resources:
  PasswordPolicy:
    Type: Community::IAM::PasswordPolicy
    Properties:
      MinimumPasswordLength: !Ref MinPasswordLength
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      AllowUsersToChangePassword: false
