name: aws-deploy

on:
  workflow_dispatch:

  workflow_run:
    branches: [ 'master' ]
    tags: [ 'v*' ]
    workflows: [ 'validate' ]
    types: [ 'completed' ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BRANCH_OR_TAG: ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # Needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::745159704268:role/sagebase-github-oidc-sage-ProviderRoleorganization-QJWJ1AG8LNON
        role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
        role-duration-seconds: 120
    - name: Copy files with the AWS CLI
      run: |
        echo aws s3 cp templates s3://bootstrap-awss3cloudformationbucket-19qromfd235z9/$REPO_NAME/$BRANCH_OR_TAG/ --recursive
